### ISSUE TITLE
Perhaps mention you need python 3.8.10 to support win7

### ISSUE THREAD

**Issue by jkommeren** [fox-it/log4j-finder#27]
Because when created with 3.9 or 3.10 the binary will not work, and result in "api-ms-win-core-path-l1-1-0.dll is missing"

It says so on the download page of python.org, but it can't hurt to mention it.

(lower is obviously also possible, but 3.8.10 is easiest to use in this case)

**Comment by yunzheng** [comment]
Thanks for the helpful feedback! it's added to the README. 

Hopefully we don't need to support Windows XP 😄
