### ISSUE TITLE
Critical issue on Windows

### ISSUE THREAD

**Issue by KrisJanssen** [fox-it/log4j-finder#35]
@yunzheng : you use standard path libraries for the lookups of files in zip files: this approach is incorrect.

![image](https://user-images.githubusercontent.com/1765614/146589268-a15fb495-9e97-43df-961b-f7723afa4fbb.png)

On windows the Exception will always be hit becasue the path for lookup of the class gets passed in the wrong format:

`'org\\apache\\logging\\log4j\\core\\lookup\\JndiLookup.class'`

rather than 

`'org/apache/logging/log4j/core/lookup/JndiLookup.class'`

And since you have defaulted to setting has_lookup = False, VULNERABLE jars are being labeled PATCHED.

This is very bad if people using windows are to rely on your tool...

The behavior is inconsistent across your codebase... this is OK:

![image](https://user-images.githubusercontent.com/1765614/146590580-703da843-a82e-48bb-8074-42c121e11bbe.png)

Furtheron it is not OK:

![image](https://user-images.githubusercontent.com/1765614/146590779-2b4bbad1-2167-4906-81d2-f7e9e7b9138f.png)

**Comment by yunzheng** [comment]
Hi, thanks for reporting the issue!

I will look into the path joining inconsistencies in Zip files on windows later, for now I merged a patch that fixes the correct intended behavious (has_lookup=True). So it should not show up as PATCHED by default now.

**Comment by KrisJanssen** [comment]
I have a fix... will send pull request

**Comment by yunzheng** [comment]
Issue should be fixed now
